## Array Creation

In [3]:
import numpy as np

# Create arrays from lists
a = np.array([1, 2, 3])
print("Array from list:", a)

# Zeros and ones
zeros = np.zeros((2, 3))
ones = np.ones((2, 3))
print("Zeros:", zeros)
print("Ones:", ones)

# Range and linspace


Array from list: [1 2 3]
Zeros: [[0. 0. 0.]
 [0. 0. 0.]]
Ones: [[1. 1. 1.]
 [1. 1. 1.]]


In [4]:
arange_array = np.arange(0, 10, 2)
linspace_array = np.linspace(0, 1, 5)
print("Arange:", arange_array)
print("Linspace:", linspace_array)


Arange: [0 2 4 6 8]
Linspace: [0.   0.25 0.5  0.75 1.  ]


In [7]:

# Identity matrix
identity = np.eye(3)
print("Identity matrix:", identity)

# Random arrays
rand_array = np.random.rand(2, 2)
randn_array = np.random.randn(2, 2)
print("Random rand:", rand_array)
print("Random randn:", randn_array)


Identity matrix: [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Random rand: [[0.33365703 0.72412309]
 [0.62776206 0.75325753]]
Random randn: [[ 0.7053375  -0.41017338]
 [ 0.70372614 -0.42693957]]


## Array Inspection

In [8]:
a = np.array([[1, 2, 3], [4, 5, 6]])
print("Shape:", a.shape)
print("Dimensions:", a.ndim)
print("Size:", a.size)
print("Data type:", a.dtype)


Shape: (2, 3)
Dimensions: 2
Size: 6
Data type: int64


## Array Manipulation

In [11]:
a = np.arange(6).reshape((2, 3))
print("Original array:", a)

# Reshape
reshaped = np.reshape(a, (3, 2))
print("Reshaped:", reshaped)


Original array: [[0 1 2]
 [3 4 5]]
Reshaped: [[0 1]
 [2 3]
 [4 5]]


In [10]:

# Ravel
flattened = np.ravel(a)
print("Flattened:", flattened)

# Transpose
transposed = np.transpose(a)
print("Transposed:", transposed)


Flattened: [0 1 2 3 4 5]
Transposed: [[0 3]
 [1 4]
 [2 5]]


In [12]:

# Concatenate
b = np.array([[7, 8, 9]])
concatenated = np.concatenate((a, b), axis=0)
print("Concatenated:", concatenated)


Concatenated: [[0 1 2]
 [3 4 5]
 [7 8 9]]


In [15]:

# Stack: 
vstacked = np.vstack((a, b))
hstacked = np.hstack((a, b.T))
print("Vstacked:", vstacked)
print("Hstacked:", hstacked)

# Split
split_arrays = np.split(a, 2)
print("Split arrays:", split_arrays)


ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 2 and the array at index 1 has size 1

## Indexing & Slicing

In [16]:
a = np.array([10, 20, 30, 40, 50])
print("Element at index 2:", a[2])
print("Slice from index 1 to 4:", a[1:4])

# Boolean indexing
print("Elements greater than 25:", a[a > 25])

# Fancy indexing
print("Elements at indices 0, 2, 4:", a[[0, 2, 4]])


Element at index 2: 30
Slice from index 1 to 4: [20 30 40]
Elements greater than 25: [30 40 50]
Elements at indices 0, 2, 4: [10 30 50]


## Mathematical Operations

In [17]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print("Add:", np.add(a, b))
print("Subtract:", np.subtract(a, b))
print("Multiply:", np.multiply(a, b))
print("Divide:", np.divide(a, b))


Add: [5 7 9]
Subtract: [-3 -3 -3]
Multiply: [ 4 10 18]
Divide: [0.25 0.4  0.5 ]


In [18]:

print("Exponential:", np.exp(a))
print("Logarithm:", np.log(a))
print("Square root:", np.sqrt(a))


Exponential: [ 2.71828183  7.3890561  20.08553692]
Logarithm: [0.         0.69314718 1.09861229]
Square root: [1.         1.41421356 1.73205081]


In [19]:

print("Sum:", np.sum(a))
print("Mean:", np.mean(a))
print("Standard deviation:", np.std(a))
print("Variance:", np.var(a))

print("Min:", np.min(a))
print("Max:", np.max(a))
print("Argmin:", np.argmin(a))
print("Argmax:", np.argmax(a))


Sum: 6
Mean: 2.0
Standard deviation: 0.816496580927726
Variance: 0.6666666666666666
Min: 1
Max: 3
Argmin: 0
Argmax: 2


## Set Operations

In [20]:
a = np.array([1, 2, 3, 4])
b = np.array([3, 4, 5, 6])

print("Unique elements in a:", np.unique(a))
print("Intersection:", np.intersect1d(a, b))
print("Union:", np.union1d(a, b))
print("Set difference (a - b):", np.setdiff1d(a, b))


Unique elements in a: [1 2 3 4]
Intersection: [3 4]
Union: [1 2 3 4 5 6]
Set difference (a - b): [1 2]


## Sorting & Searching

In [ ]:
a = np.array([5, 2, 9, 1])

print("Sorted array:", np.sort(a))
print("Indices that would sort:", np.argsort(a))

# Where condition
print("Indices where a > 4:", np.where(a > 4))


## Copying & Broadcasting

In [ ]:
a = np.array([1, 2, 3])
b = a.copy()
b[0] = 100
print("Original array:", a)
print("Copied array:", b)

# Broadcasting
a = np.array([[1], [2], [3]])
b = np.array([10, 20, 30])
broadcasted = a + b
print("Broadcasted result:
", broadcasted)
